language: java
jdk:
  - oraclejdk8
script:
  - ant

deploy:
  provider: releases
  api_key: "5da6c194f00f7636389b60f2083857443e6492a8"
  file: "/build/lib/socscore-framework.jar"
  skip_cleanup: true
  on:
    tags: true

